### ISSUE TITLE
fatal error: Heuclid/Euclid/tuple2D/Point2D. H: no such files or directories.

### ISSUE THREAD

**Issue by Smartfighting1** [Mr-tooth/AStarFootstepPlanner#1]
I met a problem.
fatal error: Heuclid/Euclid/tuple2D/Point2D. H: no such files or directories.
Can you tell me how to solve this? Where should I go to get the Point2D. H header file, 
Thanks!

**Comment by Mr-tooth** [comment]
Heuclid is another library that this respository relied on. However, it has bcome a private respository only for my team due to some other reasons. 
If you do want to use my FootstepPlanner, please send me an formal application in the following form to my email:

Personal Information:

Full Name: [Full Name]
GitHub Username: [GitHub Username]
Email Address: [Email Address]
Organization/Company (if applicable): [Organization/Company]

Purpose of Access:

ps: This respository is Non-Commercial Use Only.

My email addr is junhang2000@qq.com.
